config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: %i[create new]
  resource :session, only: [:create]

  resources :users, only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: %i[create edit update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  resources :campaigns, only: %i[index new create show] do
    resources :characters, only: %i[create edit update destroy]
    resources :creatures, only: %i[create edit update destroy]
    resources :maps, only: %i[new create edit update destroy] do
      resources :tokens, only: %i[new create edit update]
    end
  end

  resource :home, controller: :home, only: [:show]
  resource :demo, controller: :demo, only: [:show]

  root controller: :home, action: :show
end

app/models/map.rb
class Map < ApplicationRecord
  ZOOM_LEVELS = [0.25, 0.5, 1, 1.5, 2].freeze
  NORMALIZED_GRID_SIZE = 50

  belongs_to :campaign
  has_many :tokens, dependent: :destroy
  has_many :fog_areas, dependent: :destroy

  has_one_attached :image

  validates :name, presence: true
  validates :image, presence: true
  validates :grid_size, presence: true, numericality: true
  validates_inclusion_of :zoom, in: ->(map) { (0..map.zoom_max) }

  def zoom_max
    ZOOM_LEVELS.length - 1
  end

  def original_height
    image.metadata[:height]
  end

  def original_width
    image.metadata[:width]
  end

  def scaled_height
    original_height * NORMALIZED_GRID_SIZE / grid_size
  end

  def scaled_width
    original_width * NORMALIZED_GRID_SIZE / grid_size
  end

  def height
    (scaled_height * zoom_amount).round
  end

  def width
    (scaled_width * zoom_amount).round
  end

  def center_image
    maybe_analyze_image
    update(x: (width / 2).round, y: (height / 2).round)
  end

  def zoom_amount
    ZOOM_LEVELS[zoom]
  end

  def populate_characters
    campaign.characters.each do |character|
      tokens.find_or_create_by(token_template: character)
    end
  end

  def copy_token(token)
    tokens.create(
      token_template: token.token_template,
      identifier: generate_identifier(token),
      x: token.x,
      y: token.y,
      stashed: false
    )
  end

  private

  def generate_identifier(token)
    if token.token_template
      tokens.where(token_template: token.token_template).size
    elsif token.name.present?
      tokens.where(name: token.name).size
    end
  end

  def maybe_analyze_image
    if original_width.blank? || original_height.blank?
      image.analyze
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :require_login

  def new
    respond_to :js

    campaign = current_user.campaigns.find(params[:campaign_id])

    render layout: "modal", locals: {
      map: campaign.maps.new
    }
  end

  def create
    campaign = current_user.campaigns.find(params[:campaign_id])
    result = CreateNewMap.call(campaign: campaign, map_params: map_params)
    if result.success?
      head :ok
    else
      render partial: "form", locals: { map: result.map }, status: :bad_request
    end
  end

  def edit
    respond_to :js

    map = current_user.maps.find(params[:id])
    render layout: "modal", locals: { map: map }
  end

  def update
    map = current_user.maps.find(params[:id])
    result = UpdateMap.call(
      campaign: map.campaign,
      map: map,
      map_params: map_params
    )
    if result.success?
      head :ok
    else
      render partial: "form", locals: { map: map }, status: :bad_request
    end
  end

  def destroy
    map = current_user.maps.find(params[:id])
    result = DeleteMap.call(campaign: map.campaign, map: map)
    if result.success?
      head :ok
    else
      head :bad_request
    end
  end

  private

  def map_params
    params.require(:map).permit(:name, :image, :grid_size, :fog_enabled)
  end
end

app/views/maps/_form.html.erb
<%= form_with model: [map.campaign, map], html: { data: { action: "ajax:success->modal#close ajax:error->modal#onPostError" } } do |form| %>
  <% if map.errors.any? %>
    <ul class="errors">
    <% map.errors.full_messages.each do |error| %>
      <%= content_tag :li, error %>
    <% end %>
    </ul>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name, class: "input" %>

  <%= form.label :image %>
  <%= form.file_field :image, class: "input" %>

  <%= form.label :grid_size %>
  <%= form.text_field :grid_size, class: "input" %>

  <% if FogFeature.enabled_for?(current_user) %>
    <%= form.label :fog_enabled, "Enable fog" %>
    <%= form.check_box :fog_enabled, class: "input" %>
  <% end %>

  <div class="flex items-center justify-between">
    <div>
      <%= form.submit class: "btn" %>
      <%= link_to "Cancel", "#", data: { action: "click->modal#close" }, class: "inline-block mx-2 align-baseline text-sm text-gray-500 hover:text-gray-800" %>
    </div>
    <% if map.persisted? %>
      <%= link_to "Delete", campaign_map_path(map.campaign, map), method: :delete, remote: true, data: { action: "ajax:error->modal#onDeleteError", confirm: "Are you sure you want to delete #{map.name}?" }, class: "inline-block align-baseline text-sm text-red-500 hover:text-red-800" %>
    <% end %>
  </div>
<% end %>

app/views/maps/_map.html.erb
<div class="map-selector__option">
  <%= content_tag :div, nil, class: "map-selector__option-background", style: background_image(map.image) %>
  <%= content_tag :div, class: "map-selector__option-overlay", data: {
    action: "click->campaign#chooseMapOption",
    map_id: map.id
  } do %>
    <%= content_tag :span, map.name, class: "map-selector__option-text" %>
  <% end %>
  <%= link_to "Edit", edit_campaign_map_path(map.campaign, map), remote: true, class: "map-selector__option-edit hidden absolute top-0 right-0 m-2 rounded inline-block bg-black text-white text-sm px-2" %>
</div>

app/views/maps/_token_drawer.html.erb
<div class="current-map__token-drawer token-drawer flex flex-row items-center justify-start select-none bg-gray-500 mx-4 p-2 rounded-lg border whitespace-no-wrap overflow-x-auto overflow-y-hidden shadow-lg" data-target="map--tokens.drawer toggle.content" data-action="dragover->map--tokens#dragOverDrawer drop->map--tokens#dropOnDrawer toggle->toggle#toggle open->toggle#open close->toggle#close" data-toggle-target="token-drawer">
  <%= link_to new_campaign_map_token_path(map.campaign, map), remote: true, title: "New Token", class: "token new-token-link" do %>
    <span class="token__image token__image-add">+</span>
  <% end %>

  <%= render map.tokens.where(stashed: true) %>
</div>

app/views/maps/edit.html.erb
<div class="p-4">
  <h1 class="text-2xl">Edit <%= map.name %></h1>

  <hr class="my-2" />

  <%= render "form", map: map %>
</div>

app/views/maps/new.html.erb
<div class="p-4">
  <h1 class="text-2xl">New Map</h1>

  <hr class="my-2" />

  <%= render "form", map: map %>
</div>