config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: %i[create new]
  resource :session, only: [:create]

  resources :users, only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: %i[create edit update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  resources :campaigns, only: %i[index new create show] do
    resources :characters, only: %i[create edit update destroy]
    resources :creatures, only: %i[create edit update destroy]
    resources :maps, only: %i[new create edit update destroy] do
      resources :tokens, only: %i[new create edit update]
    end
  end

  resource :home, controller: :home, only: [:show]
  resource :demo, controller: :demo, only: [:show]

  root controller: :home, action: :show
end

app/models/creature.rb
class Creature < TokenTemplate
  def copy_on_place?
    true
  end
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :require_login

  def create
    creature = campaign.creatures.new(creature_params)
    if creature.save
      campaign.current_map.tokens.create(token_template: creature)
      head :ok
    else
      render(
        partial: "form",
        locals: { creature: creature },
        status: :bad_request
      )
    end
  end

  def edit
    respond_to :js

    creature = campaign.creatures.find(params[:id])
    render layout: "modal", locals: { creature: creature }
  end

  def update
    creature = campaign.creatures.find(params[:id])
    if creature.update(creature_params)
      head :ok
    else
      render(
        partial: "form",
        locals: { creature: creature },
        status: :bad_request
      )
    end
  end

  def destroy
    creature = campaign.creatures.find(params[:id])
    if creature.destroy
      redirect_to campaign, success: "Creature successfully deleted."
    else
      redirect_to edit_campaign_creature_path(campaign, creature)
    end
  end

  private

  def campaign
    current_user.campaigns.find(params[:campaign_id])
  end

  def creature_params
    params.require(:creature).permit(:name, :image, :size)
  end
end

app/views/creatures/_form.html.erb
<%= form_with model: [creature.campaign, creature], html: { data: { action: "ajax:success->modal#close ajax:error->modal#onPostError" } } do |form| %>
  <%= render "errors", model: creature %>

  <%= form.label :name %>
  <%= form.text_field :name, class: "input" %>

  <%= form.label :size %>
  <%= form.select :size, options_for_token_size, {}, class: "input" %>

  <%= form.label :image %>
  <%= form.file_field :image, class: "input" %>

  <div class="flex items-center justify-between">
    <%= form.submit class: "btn" %>
    <%= link_to "Cancel", "#", data: { action: "click->modal#close" }, class: "inline-block align-baseline text-sm text-gray-500 hover:text-gray-800" %>
    <% if creature.persisted? %>
      <%= link_to "Delete #{creature.name}", campaign_creature_path(creature.campaign, creature), method: :delete, data: { confirm: "Are you sure you want to delete #{creature.name}?" }, class: "inline-block align-baseline text-sm text-red-500 hover:text-red-800" %>
    <% end %>
  </div>

  <p class="text-sm text-gray-500 pt-4">
    Creatures are added to the current map, and available for other maps in the library.
    Creatures are copied when dragged from the token drawer.
  </p>
<% end %>

app/views/creatures/edit.html.erb
<div class="p-4">
  <h1 class="text-2xl">Edit <%= creature.name %></h1>

  <hr class="my-2" />

  <%= render "form", creature: creature %>
</div>