config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: %i[create new]
  resource :session, only: [:create]

  resources :users, only: [:create] do
    resource :password,
             controller: "clearance/passwords",
             only: %i[create edit update]
  end

  get "/sign_in" => "sessions#new", as: "sign_in"
  delete "/sign_out" => "sessions#destroy", as: "sign_out"
  get "/sign_up" => "users#new", as: "sign_up"
  resources :campaigns, only: %i[index new create show] do
    resources :characters, only: %i[create edit update destroy]
    resources :creatures, only: %i[create edit update destroy]
    resources :maps, only: %i[new create edit update destroy] do
      resources :tokens, only: %i[new create edit update]
    end
  end

  resource :home, controller: :home, only: [:show]
  resource :demo, controller: :demo, only: [:show]

  root controller: :home, action: :show
end

app/models/character.rb
class Character < TokenTemplate
  def copy_on_place?
    false
  end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  before_action :require_login

  def create
    character = campaign.characters.new(character_params)
    if character.save
      campaign.populate_characters
      head :ok
    else
      render(
        partial: "form",
        locals: { character: character },
        status: :bad_request
      )
    end
  end

  def edit
    respond_to :js

    character = campaign.characters.find(params[:id])
    render layout: "modal", locals: { character: character }
  end

  def update
    character = campaign.characters.find(params[:id])
    if character.update(character_params)
      head :ok
    else
      render(
        partial: "form",
        locals: { character: character },
        status: :bad_request
      )
    end
  end

  def destroy
    character = campaign.characters.find(params[:id])
    if character.destroy
      redirect_to campaign, success: "Character successfully deleted."
    else
      redirect_to edit_campaign_character_path(campaign, character)
    end
  end

  private

  def campaign
    current_user.campaigns.find(params[:campaign_id])
  end

  def character_params
    params.require(:character).permit(:name, :image)
  end
end

app/views/characters/_form.html.erb
<%= form_with model: [character.campaign, character], html: { data: { action: "ajax:success->modal#close ajax:error->modal#onPostError" } }  do |form| %>
  <%= render "errors", model: character %>

  <%= form.label :name %>
  <%= form.text_field :name, class: "input" %>

  <%= form.label :image %>
  <%= form.file_field :image, class: "input" %>

  <div class="flex items-center justify-between">
    <%= form.submit class: "btn" %>
    <%= link_to "Cancel", "#", data: { action: "click->modal#close" }, class: "inline-block align-baseline text-sm text-gray-500 hover:text-gray-800" %>
    <% if character.persisted? %>
      <%= link_to "Delete #{character.name}", campaign_character_path(character.campaign, character), method: :delete, data: { confirm: "Are you sure you want to delete #{character.name}?" }, class: "inline-block align-baseline text-sm text-red-500 hover:text-red-800" %>
    <% end %>
  </div>

  <p class="text-sm text-gray-500 pt-4">
    Characters are added to all maps in a campaign.
    A character can only appear on a map once.
  </p>
<% end %>

app/views/characters/edit.html.erb
<div class="p-4">
  <h1 class="text-2xl">Edit <%= character.name %></h1>

  <hr class="my-2" />

  <%= render "form", character: character %>
</div>